language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - cmake
      - libsdl2-dev

#before_install:
#  - sudo apt update

#install:
#  - sudo apt install g++-9
#  - sudo apt install cmake
#  - sudo apt install libsdl2-dev

before_script:
  - mkdir build
  - cd build

script:
  - export CC=gcc-9
  - export CXX=g++-9
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ..

