language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - cmake
      - libsdl2-dev

matrix:
  include:
    # Debug build
    - os: linux
      env: CONFIG=Debug

    # Release build
    - os: linux
      env: CONFIG=Release

before_script:
  - mkdir build-${CONFIG}
  - cd build-${CONFIG}

script:
  - export CC=gcc-9
  - export CXX=g++-9
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=${CONFIG} -G "CodeBlocks - Unix Makefiles" ..

